CREATE TABLE smusertest1.users (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(55),
    PASSWORD VARCHAR(100),
    FIRST_NAME VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    FULL_NAME VARCHAR(150),
    BIRTHDATE DATE,
    MOBILE_NO BIGINT(11),
    COMPANY VARCHAR(10),
    STORE_CODE VARCHAR(25),
    ENV_CODE VARCHAR(25),
    EMAIL VARCHAR(100),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_DATE DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE company_branch (
    COMPANY VARCHAR(10) NOT NULL,
    COMPANY_DESC VARCHAR(50),
    STORE_CODE VARCHAR(10) NOT NULL,
    STORE_DESC VARCHAR(50),
    STORE_GROUP VARCHAR(50),
    CHOSEN VARCHAR(1),
    ABBR VARCHAR(200),
    ENV_CODE VARCHAR(50),
    ENV INT,
    SECTORE_CODE VARCHAR(10) NOT NULL,
    SECTOR VARCHAR(50),
    STORE_OPENING_DATE DATE
);
